function ring2Dot()
%RING2DOT convert ring configuration to dot current
%   Configuration for rings is given in parameters.mat generated by
%   selectivity.comsol.parametersParaboleAnode
% arguments :
% - makeSim

% check if simulation need to be performed
% (take a mot of time)
if nargin ~= 0
    makeSim = varagin{1}; % 1:makeSimDots, 0:do not make sim dots
else
    makeSim = 0; % 0:do not make sim dots (default)
end
    


%% treatement of simulation

% make simulation and save files (including parameters)

% do not make simulation and load files into COMSOL server



%% generation of coordinates value (selectivity.comosl.paramatersDot)



%% least square method


% retrieve Voltage objectif (from ring simulation)


% retrieve Voltage from Dot simulation


% compute value of current and give estimation of root square sum of square
% difference {mean ERROR}: SUM([VDot(x,y,z)-Vobj]²)/numberOf(triplet(x,y,z)).







end

