Description of circle
circle
PURPOSE
send back xy coordinates of a circle of centerXY and radius R
SYNOPSIS
function [x, y] = circle(centerXY, R, nPoints)
DESCRIPTION
 send back xy coordinates of a circle of centerXY and radius R
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
drawConfigParaboleAnode
drawConfigTwoRings
fascicles
SOURCE CODE
function [x, y] = circle(centerXY, R, nPoints)
% send back xy coordinates of a circle of centerXY and radius R
    ang = linspace(0, 2*pi, nPoints);
    x = [centerXY(1)+R*cos(ang)]';
    y = [centerXY(2)+R*sin(ang)]';
    %xy = [x y];
end